### ISSUE TITLE
Class 'MongoClient' not found?

### ISSUE THREAD

**Issue by Cein-Markey** [jenssegers/laravel-mongodb#36]
Class 'MongoClient' not found in Connection.php on line 132. This is the error received when I try to run migrations - ($ php artisan migrate). Any Ideas? Thanks in advance.

**Comment by osadan** [comment]
I had the same problem . after I upgraded my Yosemite to 10.10.5 . all answers above did not solved my problem . my php --ini displayed that the mongo drive is loaded . But still got the error .
and php -v showed that I am running php version 5.6. 
What worked for me eventually copying the libexec/apace2/phpLibModule to the apace libexec directory . 
 It turned out that the apache was running version 5.5 .

**Comment by biswajitpanday** [comment]
Thanks man. I am using Linux Mint. To solve this issue i added "extension=mongo.so" (Without quotes) in two directories - 
1. /etc/php5/cli/php.ini
2. /etc/php5/apache2/php.ini

**Comment by a-ghasemi** [comment]
I have same problem on php new release, 7.0.2 . it has no mongoClient anymore and uses mongoDB extension! Now how can I use jenssegers/laravel-mongodb in my new server? please help about this asap.

**Comment by jenssegers** [comment]
@a-ghasemi There's a separate branch for this. Will be released as a new major version soon.

**Comment by a-ghasemi** [comment]
Thanks for your afforts

**Comment by mvladk** [comment]
is there expected release date for support mongodb 3.2?

**Comment by jensk** [comment]
@mvladk Version 2.3.x works well with mongodb 3.2.

**Comment by bgarrison25** [comment]
@jenssegers I see your 3.0 branch that uses mongodb pecl extension but I can't figure out how to install this with composer. if I put in "3.*" in my composer.json it yells at me because you haven't released it yet. How might I be able to use this or is there a release date for this?

**Comment by bgarrison25** [comment]
@jensk it might work well with mongodb 3.2 but php 7 now uses a new pecl extension called "mongodb" instead of "mongo" and this is causing the "MongoClient not found" error. That is what he is talking about.

**Comment by jonathanpmartins** [comment]
@bgarrison25 Use the master branch.

    "jenssegers/mongodb": "dev-master"

I think the 3.0 version is not finished yet. I use the master branch todo all my test before shipping to php7 server. The "MongoClient not found" is because you are using a old mongo client. I had a diferente issue, but I guess you can get rid of this message, compiling libmongoc again, and installing the mongo client via pecl. Look up https://github.com/mongodb/mongo-php-driver/issues/219#issuecomment-179858933

**Comment by jensk** [comment]
@bgarrison25 Indeed, php 7 requires a new driver called mongodb. (only supported by the current master branch, no release yet) Though, in my post I just answered the question about mongodb 3.2 support. ;-)

**Comment by mvladk** [comment]
@bgarrison25, exactly. finally it some how worked with "mongodb" and composer
"laravel/framework": "5.1.*",
"jenssegers/mongodb": "~3.0",

**Comment by gsolak** [comment]
@mvladk - thank you. Upgrading composer to ~3.0 jenssegers/mongodb  fixed it for me.

Running Windows +  php 7.0.1 + mongodb 3.2.1

composer.json
"laravel/framework": "5.2.*",
"jenssegers/mongodb": "^3.0"

php -i | grep
mongodb support => enabled
mongodb version => 1.1.2
mongodb stability => stable
libmongoc version => 1.1.2

The versioning is from:
https://pecl.php.net/package/mongodb

Some tips:

1) Make sure CLI php and apache php is the same (as mentioned before). Hopefully composer will fail on installation without the proper mongodb extension.
2) initially I had the .dll named as "mongo.dll" ... I recommend keeping it as "php_mongo.dll".
3) Make sure php is in Windows' path
3) http://php.net/manual/en/mongodb.installation.windows.php

**Comment by goopter** [comment]
The following php code runs fines on command line, but it failed to open in browser, with error class not found. There's one possible cause is that even the phpinfo() page shows /etc/php-zts.d/mongodb.ini is loaded, but it doesn't show anything else for mongodb module, the mongodb.so file is already defined in the ini file, spent long time can't figure out the reason, pls advise how to proceed?

Fatal error: Class 'MongoDB\Driver\Manager' not found in /var/www/vendor/mongodb/mongodb/src/Client.php on line 56

test.php

<?php
$filename='/var/www/ee14dev/vendor/autoload.php';
require $filename;
$client = new MongoDB\Client("mongodb://localhost:27017");
$collection = $client->demo->beers;
$result = $collection->insertOne( [ 'name' => 'Hinterland', 'brewery' => 'BrewDog' ] );
echo "Inserted with Object ID '{$result->getInsertedId()}'";
?>

**Comment by midium** [comment]
For all having problems with MongoClient function on php7 please check the following link:
http://stackoverflow.com/questions/34486808/installing-the-php-7-mongodb-client-driver

Basically as php7 uses a new driver class for MongoDB they has changed the function to be called.
Hope this can help

**Comment by Nigeltiany** [comment]
Lets revisit this issue a fresh [here on github](https://github.com/jenssegers/laravel-mongodb/issues/863)

**Comment by lewiswebber** [comment]
Thanks to @Rents answer I fixed this issue.
If you installed PHP with brew, do `brew services restart php70` or php56 if you use version 5.6.x.

**Comment by junibrosas** [comment]
I do not know but all the things above did not work for me.

Here is my workaround:

Install MongoDB client
https://docs.mongodb.com/manual/tutorial/install-mongodb-on-ubuntu/

Install MongoDB driver for PHP
http://www.bictor.com/2015/02/15/installing-mongodb-for-php-in-ubuntu-14-04/

If you come across with `configure: error: sasl.h not found!` error, use:

sudo apt-get install libsasl2-dev

for CentOS:
yum install cyrus-sasl-devel

**Comment by mohammad-69** [comment]
I have the same problem on homestead with php 5.6 - laravel give me the same error but strange thing is I can work with mongo in php artisan tinker and I can migrate but in browser it shows : Class 'MongoDB\Driver\Manager' not found.  I'm using "jenssegers/mongodb": "^3.1", in my composer.json file.

**Comment by gvsagar411** [comment]
i got the error as     Fatal error: Class 'Mongoclient' not found in D:\xampp\htdocs\mongo.php on line 3 
 for fixing this to get mongodb driver i have added this extension=php_mongodb.dll in php.ini file, but still the error was not fixed.

**Comment by Werter12** [comment]
Hi! For those who use vagrant/homestead (also different versions of jenssegers/mongodb for two projects on one homestead)and as I stumbled on this problem, my solution will be useful. So, homestead (6.4.0) use php cli 7.1 as default and command 'php artisan' run by default cli.  So if  you face 'MongoClient' problem, that means you use not right cli version. In order to use right cli version you have to specify 'php5.6 artisan' or 'php7.1 artisan'. Also you must have right extension in php.ini. mongo.so - for old projects, mongodb.so - for new projects.
